### ISSUE TITLE
Submit to AMO and get signed

### ISSUE THREAD

**Issue by whispy** [DaveRandom/cloud-to-butt-mozilla#8]
With the next version of FF (42), unsigned extensions will not be allowed (unless you're using a specific, unbranded, developer version of FF). Please submit this to AMO (addons.mozilla.org) and get it signed, as I'd love to keep using it. It provides laughs daily.

**Comment by DaveRandom** [comment]
Apologies for not responding to this sooner, I've been away from FOSS for a while due to other commitments.

I'll try and get this done this week.

**Comment by RMHogervorst** [comment]
Hi Dave, 
the file is not signed yet. FF flatout refuses to install it.

**Comment by DaveRandom** [comment]
Submitted.

https://addons.mozilla.org/en/firefox/addon/cloud-to-butt/

**Comment by DaveRandom** [comment]
The issue is now fully reviewed, signed, in gallery, etc etc

**Comment by RMHogervorst** [comment]
It is awesome!

Op 31 aug. 2016 19:30 schreef "Chris Wright" notifications@github.com:
